name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Need permission to write to the Releases tab now.
      # https://github.com/ncipollo/release-action/issues/208.
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: Create .venv
      run: task create-venv
    - name: Deps - Install dependencies
      run: task install-deps
    - name: Deps - Install build dependencies
      run: task install-build-deps
    - name: Deps - Install test dependencies
      run: task install-test-deps
    - name: Build - Python Package
      run: task build
    # FIXME: #2 figure out why this task throws an exit 1 after return the
    # expected parsed value?
    #
    # - name: System - run App (entrypoint)
    #   run: task test-entrypoint
    - uses: ncipollo/release-action@v1
      with:
        # Store the Python Wheel on Release page.
        artifacts: "dist/*.*"
        token: ${{ secrets.GITHUB_TOKEN }}
